[workspace]
resolver = "2"
members = ["ds-core", "ds-net", "ds-cli"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"
repository = "https://github.com/petfold/directswarm"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
todo = "warn"
dbg_macro = "warn"
